#!/bin/bash

PAD="\033[66G"
OK="\e[32mOK\e[0m"
NO="\e[31mNO\e[0m"

for w in Week*
do
    for e in "$w"/*
    do
        echo -n $(echo $e | cut -c 6-)
        cd "$e"
        if ! ./run w${w: -2}e${e:8:1} | grep NO > /dev/null
        then
            echo -e "$PAD[ $OK ]"
        else
            echo -e "$PAD[ $NO ]"
        fi
        cd ../..
    done
done
