#!/bin/bash

PAD="\033[66G"
OK="\e[32mOK\e[0m"
WA="\e[33mWA\e[0m"
NO="\e[31mNO\e[0m"

for w in Week*
do
    for e in "$w"/*
    do
        echo -n $(echo $e | cut -c 6-)
        cd "$e"
        RES=$(./run w${w: -2}e${e:8:1})
        if ! echo "$RES" | grep NO > /dev/null
        then
            echo -e "$PAD[ $OK ]"
        else
            if echo "$RES" | grep OK > /dev/null
            then
                echo -e "$PAD[ $WA ]"
            else
                echo -e "$PAD[ $NO ]"
            fi    
        fi
        cd ../..
    done
done
